// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using UserConnections.Infrastructure.Persistence;

#nullable disable

namespace UserConnections.Infrastructure.Migrations
{
    [DbContext(typeof(UserConnectionDbContext))]
    [Migration("20250427205053_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0-preview.7.24405.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("UserConnections.Infrastructure.Entities.ConnectionEventOutbox", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<DateTime>("ConnectionTimeUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ConnectionTimeUtc");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreatedAtUtc");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar")
                        .HasColumnName("IpAddress");

                    b.Property<DateTime?>("ProcessedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ProcessedAtUtc");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("UserId");

                    b.HasKey("Id");

                    b.HasIndex("ProcessedAtUtc");

                    b.ToTable("ConnectionEventsOutbox", (string)null);
                });

            modelBuilder.Entity("UserConnections.Infrastructure.Entities.UserConnectionEntity", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("UserId");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("varchar")
                        .HasColumnName("IpAddress");

                    b.Property<DateTime>("LastConnectionUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("LastConnectionUtc");

                    b.HasKey("UserId", "IpAddress");

                    b.HasIndex("IpAddress");

                    b.ToTable("UserConnections", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
